version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=recipes_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - APP_ENV=development
    restart: always
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: