// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"database/sql"
	"time"
)

type Ingredient struct {
	ID        int32
	Name      string
	CreatedOn time.Time
	UpdatedOn time.Time
}

type IngredientQuantityType struct {
	ID             int32
	IngredientID   sql.NullInt32
	QuantityTypeID sql.NullInt32
	Amount         int32
	CreatedOn      time.Time
	UpdatedOn      time.Time
}

type QuantityType struct {
	ID        int32
	Type      string
	CreatedOn time.Time
	UpdatedOn time.Time
}

type Recipe struct {
	ID           int32
	RecipeUserID int32
	RecipeName   string
	RecipeSteps  string
	CreatedOn    time.Time
	UpdatedOn    time.Time
}

type RecipeUser struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedOn time.Time
	UpdatedOn time.Time
}
